---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: document
  path: customer_readme.md
  label: Informationen
  match: "**/*"
- type: heading
  label: Seiteninhalt
- type: document
  path: content/_index.md
  label: Startseite
  templates:
  - standard
- type: document
  path: content/über-uns.md
  label: Über uns
  templates:
  - standard
- type: document
  path: content/aktuelles.md
  label: Aktuelles
  templates:
  - standard
- type: document
  path: content/beratung.md
  label: Beratung
  templates:
  - standard
- type: document
  path: content/erfa.md
  label: Erfa
  templates:
  - standard
- type: document
  path: content/seminare.md
  label: Seminare
  templates:
  - standard
- type: document
  path: content/downloads.md
  label: Downloads
  templates:
  - downloads
- type: document
  path: content/partner.md
  label: Partner
  templates:
  - standard
- type: document
  path: content/kontakt.md
  label: Kontakt
  templates:
  - standard
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.69.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.69.0
